# Generated by Django 2.2.2 on 2019-06-30 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0002_auto_20190630_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1a95c0d-d7ae-4009-bd8a-fc15b21b9b91'), editable=False, primary_key=True, serialize=False),
        ),
    ]
