# Generated by Django 2.2.2 on 2019-06-30 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0003_auto_20190630_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cff46734-7871-47f5-aabe-0839b8b59071'), editable=False, primary_key=True, serialize=False),
        ),
    ]
