# Generated by Django 2.2.2 on 2019-06-30 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0004_auto_20190630_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('572380f1-a101-4e76-8483-e949f283f959'), editable=False, primary_key=True, serialize=False),
        ),
    ]
