# Generated by Django 2.2.2 on 2019-06-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0005_auto_20190630_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39babe0b-c1e0-4bcb-856e-a5586dd47ddb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
