# Generated by Django 2.2.2 on 2019-06-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0006_auto_20190630_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dba2d49-9a6b-43fc-9d09-45c3d0fab736'), editable=False, primary_key=True, serialize=False),
        ),
    ]
