# Generated by Django 2.2.2 on 2019-06-30 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0007_auto_20190630_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfcf4070-b3be-423f-a436-90692ef63b53'), editable=False, primary_key=True, serialize=False),
        ),
    ]
