# Generated by Django 2.2.2 on 2019-06-30 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0009_auto_20190630_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d7f0435-9335-4555-9cec-550ea71b19b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
