# Generated by Django 2.2.2 on 2019-06-30 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0010_auto_20190630_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95c1dfed-9941-4ce1-ad71-fa61dd2889c7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
