# Generated by Django 2.2.2 on 2019-06-30 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0011_auto_20190630_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8be2e21-ce09-4797-8365-9cd3995b13c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
