# Generated by Django 2.2.2 on 2019-07-01 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0012_auto_20190630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5935d08e-db11-465f-aeb9-2438e511ed07'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
