# Generated by Django 2.2.2 on 2019-07-01 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0013_auto_20190701_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
