# Generated by Django 2.2.3 on 2019-07-06 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('starting_date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_subject', models.CharField(max_length=250)),
                ('task_details', models.CharField(max_length=500)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Complete'), ('pending', 'Pending')], default='pending', max_length=150)),
                ('work_to', models.ForeignKey(limit_choices_to={'category': 'task-manager'}, on_delete=django.db.models.deletion.CASCADE, to='manager_login.Manager')),
            ],
        ),
    ]
