# Generated by Django 2.2.2 on 2019-06-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_login', '0011_auto_20190630_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=250)),
                ('task_details', models.CharField(max_length=500)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Complete'), ('pending', 'Pending')], default='pending', max_length=150)),
                ('work_to', models.ForeignKey(limit_choices_to={'category': 'task-manager'}, on_delete=django.db.models.deletion.CASCADE, to='manager_login.Manager')),
            ],
        ),
    ]
