# Generated by Django 2.2.2 on 2019-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20190701_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
